USE hotel_management;
GO

-- Create the ANH_HANG_PHONG table
CREATE TABLE ANH_HANG_PHONG (
                            ID_ANH_HANG_PHONG VARCHAR(45) PRIMARY KEY,
                            URL_ANH NVARCHAR(MAX) NOT NULL,
                            ID_HANG_PHONG BIGINT NOT NULL,
                            FOREIGN KEY (ID_HANG_PHONG) REFERENCES HANG_PHONG(ID_HANG_PHONG)
);
GO

DECLARE @ID_HANG_PHONG_CURSOR CURSOR;
SET @ID_HANG_PHONG_CURSOR = CURSOR FOR SELECT ID_HANG_PHONG FROM HANG_PHONG;
OPEN @ID_HANG_PHONG_CURSOR;

DECLARE @ID_HANG_PHONG BIGINT;
FETCH NEXT FROM @ID_HANG_PHONG_CURSOR INTO @ID_HANG_PHONG;
WHILE @@FETCH_STATUS = 0
    BEGIN
        INSERT INTO ANH_HANG_PHONG(ID_ANH_HANG_PHONG, URL_ANH, ID_HANG_PHONG)
        VALUES (NEWID(), 'test_class_room.jpg', @ID_HANG_PHONG);

        -- Fetch the next rows
        FETCH NEXT FROM @ID_HANG_PHONG_CURSOR INTO @ID_HANG_PHONG;
    END