USE hotel_management;

-- add DON_GIA to CT_PHIEU_THUE
ALTER TABLE CT_PHIEU_THUE
    ADD DON_GIA DECIMAL(10, 2) NOT NULL DEFAULT 0;

-- add TRANG_THAI to CT_PHIEU_DAT
ALTER TABLE CT_PHIEU_DAT
    ADD TRANG_THAI BIT NOT NULL DEFAULT 0;

