USE hotel_management;
GO

DECLARE @ID_HANG_PHONG_CURSOR CURSOR;
SET @ID_HANG_PHONG_CURSOR = CURSOR FOR SELECT ID_HANG_PHONG FROM HANG_PHONG;
OPEN @ID_HANG_PHONG_CURSOR;

DECLARE @ID_HANG_PHONG BIGINT;
FETCH NEXT FROM @ID_HANG_PHONG_CURSOR INTO @ID_HANG_PHONG;
WHILE @@FETCH_STATUS = 0
BEGIN
INSERT INTO GIA_HANG_PHONG(ID_HANG_PHONG, NGAYAPDUNG, NGAY_THIET_LAP, GIA, ID_NV)
VALUES (@ID_HANG_PHONG, GETDATE(), GETDATE(), 100.00, 'EMPL00001');

-- Fetch the next rows
FETCH NEXT FROM @ID_HANG_PHONG_CURSOR INTO @ID_HANG_PHONG;
END