USE [hotel_management]
GO

-- Create the VIEW_ROOM_CLASS_LIST view
CREATE VIEW [VIEW_ROOM_CLASS_LIST] AS
    SELECT HP.*, KP.TEN_KP, LP.TEN_LP
    FROM HANG_PHONG HP
    JOIN KIEU_PHONG KP on HP.ID_KP = KP.ID_KP
    JOIN LOAI_PHONG LP on HP.ID_LP = LP.ID_LP
;



