USE [hotel_management]
GO
/****** Object:  StoredProcedure [dbo].[SP_UPDATE_STATUS_RESERVATION]    Script Date: 11/1/2023 11:03:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Tạo Stored Procedure
CREATE PROCEDURE [dbo].[SP_UPDATE_STATUS_RESERVATION]
AS
BEGIN
    UPDATE dbo.PHIEU_DAT
    SET TRANG_THAI = 3
    WHERE GETDATE() > NGAY_BD_THUE and GETDATE() <= NGAY_DI and TRANG_THAI <> 2;
	UPDATE dbo.PHIEU_DAT
    SET TRANG_THAI = 0
    WHERE GETDATE() > NGAY_DI and TRANG_THAI <> 2;
END;
