alter table HANG_PHONG
    add constraint HANG_PHONG_pk
        unique (ID_KP, ID_LP)

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00001', 'RK00001')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00001', 'RK00002')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00001', 'RK00003')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00002', 'RK00002')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00002', 'RK00004')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00003', 'RK00001')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00003', 'RK00002')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00003', 'RK00003')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00003', 'RK00004')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00005', 'RK00001')

INSERT INTO HANG_PHONG (MO_TA, SO_LUONG_KHACH_O, ID_KP, ID_LP)
VALUES ('', '', 'RT00005', 'RK00002')

